---
- name: Setting Up RHSM
  redhat_subscription:
      username: "{{ rhsm_username }}"
      password: "{{ rhsm_password }}"
      pool_ids: "{{ rhsm_pool_id }}"
      force_register: yes
  when: enable_rhsm|bool == True
#####
##### RHSM registration works only when its enabled during workflow process
#####
- name: Disabling all repos
  rhsm_repository:
      state: disabled 
      name: "*"
- name: Setting up repos
  rhsm_repository:
      state: present 
      name: "{{ item }}" 
  when: 
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "8"
  with_items:
    - "{{rhsm_rhel8_repos}}"
- name: Setting up Repos for RHEL7 
  rhsm_repository:
      state: present 
      name: "{{ item }}" 
  when: 
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "7"
  with_items:
    - "{{ rhsm_rhel7_repos }}"
- name: Upgrading package to the latest versions
  dnf:
    state: latest
    name: "*"
  when: 
    - ansible_distribution == "RedHat"
    - ansible_distribution_major_version == "8"
##### Installing some packages for testing purposes
- name: Installing packages for basework
  package:
      state: present
      name: "{{ item }}"
  with_items:
    - "{{rhel_additional_software}}"
 
- name: Enabling firewalld
  service:
    name: firewalld
    state: started
- name: Starring firewalld
  service:
    name: firewalld
    state: started
- name: Enabling Nessecary ports
  firewalld:
    state: enabled
    port: "{{ item }}"
    permanent: True
  with_items: 
    - "{{ rhel_ports_to_open }}"

- name: Reload FirewallCMD
  command: firewall-cmd --reload
- name: Restart Firewalld
  service:
      name: firewalld
      state: restarted

### Creating users for key-based deployment

- name: creating user
  user:
      name: "{{ deploy_username }}"
      comment: "Username for ceph deployment" 
      create_home: yes 
      password: "{{ user_crypted_password }}"
      groups: wheel 
- name: adding nessecary configuration for sudo
  lineinfile:
      path: "/etc/sudoers.d/{{ deploy_username }}" # required. The file to modify.,Before 2.3 this option was only usable as I(dest), I(destfile) and I(name).
      create: yes # not required. Used with C(state=present). If specified, the file will be created if it does not already exist. By default it will fail if the file is missing.
      state: present # not required. choices: absent;present. Whether the line should be there or not.
      line: "{{ deploy_username }}	ALL=(ALL)	NOPASSWD: ALL"
      mode: 0440
- name: Adding keys to the user
  authorized_key:
      user: "{{ deploy_username }}" 
      comment: undefined 
      key: "{{ deploy_user_key }}" 
      state: present 

### installing ceph-ansible on bastion node 


- name: Block of preparing bastion
  block:
    - name: installing cockpit
      package:
        name: cockpit
        state: present
    - name: enabling cockpit
      service:
        name: cockpit.socket
        enabled: yes
        state: started
    - name: enabling ports for cockpit
      firewalld:
        port: 9090/tcp
        state: enabled
        immediate: true
        permanent: true
    - name: installing ceph-ansible
      package:
        name: cockpit-ceph-installer
        state: present
  when: "'bastion' in group_names"
